---
title: "Sincro"
format:
  html:
    toc: true
    theme: litera
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    self-contained: true
execute:
  echo: false
  warning: false
---

```{r}
#| include: false
#| 

library(magick)
library(tidyverse)
library(readxl)
library(reshape2)
library(kableExtra)
library(here)

# Datos
source("R/Climatelabs_original.R")
source("R/1-Data-sincro.R")

```


# Objectif:

> Cette présentation fait un anlyse Globala Sinchro pour le Projet Climatelabs


# Gantt Original de Climatelabs

```{r Gantt, include=TRUE, fig.retina=3, out.width='100%'}
Gannt <- image_read_pdf('Planning/planning.pdf', density = 200)
#image_scale(, "2000")
Gannt
```

---


# Sincro Initial


```{r,}
Climatelabs.original %>% 
   select(WP, Role, Unit.cost, Jours.GA) %>% 
   set_names("WP", "Role", "Coût de chaque Rôle (Euros/Jour)", "Jours (G.A.)") %>% 
   kbl(booktabs = T, digits = 2, escape = F,   padding = 0, format = "html", table.attr='class="myTable"' ) %>% 
   kable_styling(latex_options = "striped", full_width = T, font_size = 14) %>% 
   row_spec( c(4, 8, 12, 16), extra_css = "border-bottom: 1px solid") %>% 
   collapse_rows(columns = 1, valign = "middle") 
```


# Total of days

```{r}
Climatelabs.original %>% group_by(Role) %>% summarise(Days = sum(Jours.GA)) %>% 
   kbl(booktabs = T, digits = 2, escape = F,   padding = 0, format = "html", table.attr='class="myTable"' ) %>% 
   kable_styling(latex_options = "striped", full_width = T, font_size = 14) 
```

---


# UL Sinchro: Janvier 2020 - `r format(Sys.time(), "%b %d %Y")`

```{r, include=TRUE}
Tabla.Sinchro <- Sincro
Tabla.Sinchro[Tabla.Sinchro == 0] <- NA
#Tabla.Sinchro %>% mutate_if(is.double, as.character) -> Tabla.Sinchro


#Tabla.Sinchro$WP %>% levels()
Tabla.Sinchro$WP <- 
   factor(Tabla.Sinchro$WP, 
          levels = c("Preparation",
                     "Development", 
                     "Quality Plan",
                     "Dissemination\nexploitation", 
                     "Management"))

Tabla.Sinchro %>% arrange(WP) %>% 
  kbl(booktabs = T,  format = "html", table.attr='class="myTable"') %>% 
  kable_styling(latex_options = "striped", full_width = T, font_size = 10 ) %>%
  collapse_rows(columns = 1:2, valign = "middle") 

```


---

# Sinchro UL - ClimateLabs



```{r}
Sincro.UL <- Sincro %>% group_by(WP, Role) %>% summarise(Sincro.UL = sum(Total))
# Joinning 
Summary <- 
   Climatelabs.original %>% left_join(Sincro.UL, by=c("WP", "Role")) %>% 
   select(WP:Unit.cost, Sincro.UL)

Summary$WP <- 
   factor(Summary$WP, 
          levels = c("Preparation",
                     "Development", 
                     "Quality Plan",
                     "Dissemination\nexploitation", 
                     "Management"))


Summary %>% select(-Unit.cost) %>% 
   kbl(booktabs = T) %>% 
  kable_styling(latex_options = "striped", full_width = T, font_size = 9) %>% 
  collapse_rows(columns = 1:2, valign = "middle") 

```



```{r}
Summary %>% group_by(Role) %>% summarise(Days = sum(Jours.GA),
                                         Days_UL = sum(Sincro.UL, na.rm = TRUE),
                                         Days_to_declare = Days - Days_UL) %>% 
   kbl(booktabs = T, digits = 2, escape = F,   padding = 0, format = "html", table.attr='class="myTable"' ) %>% 
   kable_styling(latex_options = "striped", full_width = T, font_size = 20) 
```


---

# Graph

```{r, out.width='90%', fig.width=7, fig.height=3}

Summary %>% select(-Unit.cost) %>% 
   pivot_longer(cols = Jours.GA:Sincro.UL,
                names_to = "Type") %>% 
   ggplot(aes(x = WP, y = value, fill = Type))+
   geom_bar( stat = "Identity", position="dodge") +
   #scale_y_continuous(limits = c(0, 50))  +
   coord_flip() +
   facet_grid(. ~ Role, scales = "free_x")

```


Sinchro: Janvier 2020 - `r format(Sys.time(), "%b %d %Y")`