---
title: "Planning ClimateLabs Incubation Program -CLIP-"
#output: html_document
classoption: 
  - landscape
  - a3paper
geometry: margin=1cm
header-includes:
  - \usepackage{pgfgantt}
  - \usepackage{textcomp}
  - \usepackage{graphicx}
  - \usepackage{tikz}
#bibliography: library.bib
output: pdf_document
#csl: ieee.csl
link-citations: yes
linkcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\ganttset{%
        calendar week text={%
            W\currentweek
        }%
    }

\noindent\resizebox{\textwidth}{!}{
\begin{tikzpicture}[x=.5cm, y=1cm]

\begin{ganttchart}[vgrid, hgrid, 
   time slot format = isodate, 
   bar/.append style={fill=blue!50, rounded corners=3pt},
	newline shortcut=true,
	%today={\the\year-\the\month-\the\day}, 
	%today offset= .3,
	y unit chart=0.6cm,
	x unit = 0.2cm,
	bar label node/.append style={align=left},
	milestone/.append style={fill=blue, rounded corners=1pt},
	milestone label font=\color{blue},
	time slot unit = day ]{2021-02-01}{2021-10-15}
	
	 \gantttitlecalendar{year, month=shortname,  week=1} \\
	
\ganttgroup[bar/.append style={fill=blue}]{Preparation of CLIP}{2021-02-01}{2021-04-01}    \\ 	
	\ganttgroup{Production of Conceptual Videos}{2021-02-01}{2021-04-01}    \\ 
	
	\ganttgroup{Production of Case Studies Videos}{2021-02-01}{2021-04-01}    \\ 



\ganttset{bar incomplete/.append style={fill=red!40},
    group/.append style={draw=black, fill=red},}
    
\ganttgroup{Fundamentals and Principles}{2021-04-01}{2021-05-01}    \\ 

   \ganttbar[name=T1.1]{Webinar Introduccion}{2021-04-01}{2021-04-02}  \\
   \ganttbar[name=T1.2]{Partners take Module 1}{2021-04-05}{2021-04-16}  \\
   \ganttbar[name=T1.3]{Online tutorship bu EU Universities}{2021-04-19}{2021-04-23}  \\
   \ganttbar[name=T1.4]{Delivrable from Universities}{2021-04-26}{2021-04-30}  \\


\ganttset{bar incomplete/.append style={fill=blue!40},
    group/.append style={draw=black, fill=blue},}

   
\ganttgroup{Strategic Intent \& Operation Design}{2021-05-03}{2021-08-20} \\ 

   \ganttgroup{Strategic Intent}{2021-05-03}{2021-05-28} \\ 
   
   \ganttbar[name=T2.1]{Webinar Introduccion}{2021-05-06}{2021-05-07}  \\
   \ganttbar[name=T2.2]{Partners Take Module 2}{2021-05-10}{2021-05-21}  \\
   \ganttbar[name=T2.3]{Online tutorship bu EU Universities}{2021-05-10}{2021-04-21}  \\
   \ganttbar[name=T2.4]{Delivrable from Universities}{2021-05-24}{2021-05-28}  \\


   \ganttgroup{Physical Embodiment}{2021-05-31}{2021-06-25} \\
   
   \ganttbar[name=T3.1]{Webinar Introduccion}{2021-06-03}{2021-06-04}  \\
   \ganttbar[name=T3.2]{Partners Take Module 3}{2021-06-07}{2021-06-18}  \\
   \ganttbar[name=T3.3]{Online tutorship bu EU Universities}{2021-06-21}{2021-06-25}  \\
   \ganttbar[name=T3.4]{Delivrable from Universities}{2021-06-28}{2021-07-02}  \\

  \ganttgroup{Process of Use \& Outcomes}{2021-07-05}{2021-08-20} \\ 

   
   \ganttbar[name=T4.1]{Webinar Introduccion}{2021-07-08}{2021-07-09}  \\
   \ganttbar[name=T4.2]{Partners Take Module 4}{2021-07-12}{2021-07-23}  \\
   \ganttbar[name=T4.3]{Online tutorship bu EU Universities}{2021-07-26}{2021-07-30}  \\
   

   %Vacances
   \ganttbar[bar/.append style={fill=green}]{Holidays on Europe}{2021-08-01}{2021-08-20} \\
   \ganttbar[name=T4.4]{Delivrable from Universities}{2021-08-23}{2021-08-27}  \\
   

\ganttset{bar incomplete/.append style={fill=Green!40},
    group/.append style={draw=black, fill=Green},}

   
\ganttgroup{Follow up \& evaluation}{2021-08-30}{2021-09-24} \\ 

   \ganttgroup{Assessment \& Adaptation}{2021-08-23}{2021-10-08} \\ 
   
   \ganttbar[name=T5.1]{Webinar Introduccion}{2021-09-09}{2021-09-10}  \\
   \ganttbar[name=T5.2]{Partners Take Module 3}{2021-09-13}{2021-09-24}  \\
   \ganttbar[name=T5.3]{Online tutorship bu EU Universities}{2021-09-27}{2021-10-01}  \\
   \ganttbar[name=T5.4]{Delivrable from Universities}{2021-10-04}{2021-10-08}  \\


\ganttgroup{Operationalizing}{2021-10-11}{2021-10-15} \\ 
   \ganttgroup{Pilot Project}{2021-10-14}{2021-10-15} \\ 
   
   \ganttbar[name=T6.1]{Webinar Closing the CLIP}{2021-10-14}{2021-10-15}  \\
   \ganttbar[name=T6.1]{Start of Pilot  Projects}{2021-10-14}{2021-10-15}  \\

   
 %  \ganttbar[name=T2]{T6.2 Manufacturing of wood furniture demonstrator}{2021-10}{2022-07}\\ 
 %  \ganttbar[name=T3]{T6.3 3D printing of wood demonstrator}{2021-10}{2022-07}\\ 
 %  \ganttbar[name=T4,  progress=5]{T6.4 3D printing of recycled plastic demonstrator}{2021-10}{2022-07}\\ 
 %  \ganttbar[name=T5]{T6.5 Smartification demonstrator}{2021-10}{2022-07}\\ 
 %  
 %  \ganttbar[name=T6]{T6.6 Test and evaluation of results}{2022-04}{2022-07}\\ 
 %  \ganttbar[name=T4]{T6.7 Analysis of the Gender Dimension in the DIT process}{2021-12}{2022-07}\\ 
 %  
 %  \ganttmilestone[name=Mile1]{Delivrable}{2022-07} \ganttnewline
 %  
 %  \ganttgroup{WP 7: Communication, Dissemination and Exploitation}{2020-12}{2022-10} \\ 
   
   
   
   %\ganttlink{T1.1}{T1.2}
   %\ganttlink{T1.1}{T1.3}
   %\ganttlink{T1.1}{T1.4}
   %\ganttlink{T1.1}{T1.5}
   %\ganttlink{T1.4}{Mile1}


\end{ganttchart}
\end{tikzpicture}
}

Last Updated :  `r format(Sys.time(), '%d %B, %Y')`

